# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 395b1b49abf369c260ae373516c20f09cccf1d5c3c14a315f7ba0016ba8935cf06e19f8d02d5c5d45d5785d18895b8a232aff5ba1186d33db9b5fb1900883708

test:
  secret_key_base: e8c39993be91bf956b072119ec5ab93ae07bac0bb9aada29d112dbdcd993f08ddf8a25aea6f89723cea37ca8fcc7e823dd951b5d63284e17971f319e95cd96fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
